### index movie
GET http://localhost:3000/movies.json
### index actor
GET http://localhost:3000/actors.json
### show movie
GET http://localhost:3000/movies/1.json
### show actor
GET http://localhost:3000/actors/1.json

### create movie
POST http://localhost:3000/movies.json 
Content-Type: application/json

{
  "title": "test title",
  "year": "test year", 
  "plot": "test plot",
  "director": "test director",
  "english": ""
}
### create actor
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "test first name",
  "last_name": "test last name",
  "known_for": "test known for",
  "age": 15,
  "movie_id": 1
}
### update movie
PATCH http://localhost:3000/movies/6.json
Content-Type: application/json

{"title": "Tombstone"}
### update actor
PATCH http://localhost:3000/actors/14.json
Content-Type: application/json

{"first_name": "Paul"}
### movie destroy
DELETE http://localhost:3000/movies/6.json
### actor destroy
DELETE http://localhost:3000/actors/14.json
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "MacGregor",
  "email": "mac@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### movie genre create
POST http://localhost:3000/movie_genre.json
Content-Type: application/json

{
  "movie_id": 6,
  "genre_id": 3
}