### index movie
GET http://localhost:3000/movies.json
### show movie
GET http://localhost:3000/movies/1.json
### create movie
POST http://localhost:3000/movies.json 
Content-Type: application/json
{
  "title": "test title",
  "name": "test name", 
  "description": "test description"
}
### update movie
PATCH http://localhost:3000/movies/2.json
Content-Type: application/json

{"name": "Matrix"}

### movie destroy
DELETE http://localhost:3000/movies/2.json