### index movie
GET http://localhost:3000/movies.json
### index actor
GET http://localhost:3000/actors.json
### show movie
GET http://localhost:3000/movies/1.json
### show actor
GET http://localhost:3000/actors/1.json
### create movie
POST http://localhost:3000/movies.json 
Content-Type: application/json

{
  "title": "test title",
  "year": "test year", 
  "plot": "test plot",
  "director": "test director",
  "english": ""
}
### create actor
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "test first name",
  "last_name": "test last name",
  "known_for": "test known for"
}
### update movie
PATCH http://localhost:3000/movies/2.json
Content-Type: application/json

{"title": "Tombstone"}
### update actor
PATCH http://localhost:3000/actors/2.json
Content-Type: application/json

{"first_name": "Paul"}
### movie destroy
DELETE http://localhost:3000/movies/4.json
### actor destroy
DELETE http://localhost:3000/actors/13.json